version: '3.10'

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - shoplist_db:/var/lib/postgresql/data
    env_file:
      - src/core/config/.env
    ports:
      - "5433:5432"
    container_name: shoplist-db

  back:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./docker/start_app.sh
    volumes:
      - ./:/code/
    ports:
      - "8000:8000"
    env_file:
      - src/core/config/.env
    container_name: shoplist-back
    restart: always

volumes:
  shoplist_db:
