version: '3.10'

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - shoplist_db:/var/lib/postgresql/data
    env_file:
      - src/core/config/.env
    ports:
      - "5432:5432"
    networks:
      - shoplist-network
    container_name: shoplist-db

  back:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./docker/start_app.sh
    volumes:
      - ./:/code/
    ports:
      - "8000:8000"
    env_file:
      - src/core/config/.env
    networks:
      - shoplist-network
    container_name: shoplist-back
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/data
    networks:
      - shoplist-network

    container_name: shoplist-redis

volumes:
  shoplist_db:
  redis_storage:

networks:
  shoplist-network: