"""Change type of column phone_number in User model

Revision ID: 7f25f489dfc8
Revises: 4f8519fda689
Create Date: 2023-01-26 18:39:18.080052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f25f489dfc8'
down_revision = '4f8519fda689'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
